### ISSUE TITLE
Suggestion - use a different color for the Starting At bit of text 

### ISSUE THREAD

**Issue by jzhu01** [erholmes/prj-rev-bwfs-dasmoto#2]
Seen here: https://github.com/erholmes/prj-rev-bwfs-dasmoto/blob/master/style/index.css#L31-L34

Since these are supposed to mimic links, it looks as though it has already been clicked on. I suggest using a brighter color for it!

**Comment by erholmes** [comment]
Thanks for the comments! That makes sense!
